# Template for whole genome Illumina variant calling with GATK pipeline
---
details:
  - upload:
      dir: /home/ubuntu/local_results
    files: [/home/ubuntu/cloud_mountpoint/SRR1597834/NA06985.mapped.ILLUMINA.bwa.CEU.low_coverage.20120522.bam]
    analysis: variant2
    genome_build: GRCh37
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    description: SRR1597834
    algorithm:
      bam_clean: fixrg
      #aligner: bwa
      recalibrate: gatk
      variantcaller: gatk-haplotype
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
